[package]
name = "tokio-test"
version = "0.1.0"
authors = ["Matt Kline"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
fastcdc = "1.0"
futures = "0.3"
log = "0.4"
memmap = "0.7"
simplelog = "0.7"
structopt = "0.3.8"

[dependencies.tokio]
version = "0.2"
features = [
    "fs",
    "macros",
    "rt-threaded"
]
