[package]
name = "backup-test"
version = "0.1.0"
authors = ["Matt Kline"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
fastcdc = "1.0"
log = "0.4"
memmap = "0.7"
sha2 = "0.9"
simplelog = "0.7"
structopt = "0.3.8"
rayon = "1.4"
