[package]
name = "backpak"
version = "0.1.0"
authors = ["Matt Kline"]
edition = "2018"
resolver = "2" # Try new dependency resolver from Rust 1.51

[profile.dev]
opt-level = 2 # We want optimization even for debug builds for all the hashing.
incremental = true # Iterate faster

[profile.release]
debug = true

[dependencies]
atty = "0.2"
anyhow = "1.0"
enum-map = "0.6"
fastcdc = "1.0"
hex = "0.4"
hostname = "0.3"
lazy_static = "1.0"
log = "0.4"
memmap = "0.7"
num_cpus = "1.0"
rayon = "1.4"
serde = "1.0"
serde_bytes = "0.11"
serde_cbor = "0.11"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.9"
structopt = "0.3.8"
tempfile = "3.0"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.simplelog]
version = "0.10"
git = "https://github.com/mrkline/simplelog.rs"
branch = "optional-color"
features = ["test", "termcolor"]

[dependencies.zstd]
version = "0.5"
features = ["zstdmt"]

[dev-dependencies]
assert_cmd = "1.0"
env_logger = "0.8"
nix = "0.19"
walkdir = "2.0"
