[package]
name = "backup-test"
version = "0.1.0"
authors = ["Matt Kline"]
edition = "2018"

[dependencies]
anyhow = "1.0"
fastcdc = "1.0"
hex = "0.4"
log = "0.4"
memmap = "0.7"
num_cpus = "1.0"
sha2 = "0.9"
serde = "1.0"
serde_bytes = "0.11"
serde_derive = "1.0"
serde_cbor = "0.11"
serde_json = "1.0"
simplelog = "0.7"
structopt = "0.3.8"
rayon = "1.4"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.zstd]
version = "0.5"
features = ["zstdmt"]

[dev-dependencies]
tempfile = "3.0"
